name: Java CI

on:
  push:
    paths: ['Installation_Test']
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE USER 'testuser'@'localhost' IDENTIFIED BY 'password';" -uroot -proot
          mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'testuser'@'localhost';" -uroot -proot
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven Installation_Test
        run: |
          cd Installation_Test 
          mvn compile
          mvn exec:java -Dexec.mainClass="popbr.InstallationTest"
      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
            name: my-artifact
            path: Installation_Test/target/GFGsheet.xlsx
