name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DB_USER: 'testuser'
      DB_PASSWORD: 'password'
      DB_HOST: localhost

    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE wordpress_test;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven Installation_Test
        run: |
          cd Installation_Test 
          mvn compile
          mvn exec:java -Dexec.mainClass="popbr.InstallationTest"
